In [3]:
import numpy as np

In [4]:
N = 53
vec=[1, 1, 1, 1, 1, 0, 0,1,1,1,1,0,0,0,1,1,1,1,1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0,1,1,1,1,0,0,0,1,1,1,1,0,0,0,1,1,1,1,0,0,0]

In [5]:
len(vec)

53

In [6]:
N = 9
vec = [1, 0, 1, 1, 1, 1, 1, 1, 0]

In [7]:
N = 11
vec = [1, 1, 1, 0, 1,1, 1, 0, 1, 1, 0]

In [8]:
vec_np = np.array(vec, dtype=np.int32)

In [9]:
print(vec_np)

[1 1 1 0 1 1 1 0 1 1 0]


In [10]:
# 行列作成
box = np.zeros((N,N-6),dtype=int)
for i in range(N-6):
    box[i:i+7,i] = 1
print(box)

[[1 0 0 0 0]
 [1 1 0 0 0]
 [1 1 1 0 0]
 [1 1 1 1 0]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [0 1 1 1 1]
 [0 0 1 1 1]
 [0 0 0 1 1]
 [0 0 0 0 1]]


In [11]:
vec_ans = np.dot(vec_np,box)

In [12]:
vec_ans[vec_ans <= 5] = 1

In [13]:
vec_ans

array([6, 1, 1, 1, 1])

In [14]:
ans = []
count = 0
for i in range(N-6):
    if vec_ans[i] == 1:
        count += 1
    else:
        ans.append(count)
        count = 0
ans.append(count)

if max(ans) == 0:
    print(max(ans))
else:
    print(max(ans) + 6)

10


In [15]:
ans

[0, 4]

# 平面状の移動シミュレーションについて